### ISSUE TITLE
Text does not appear when typing

### ISSUE THREAD

**Issue by qzmarco** [spring-projects/spring-ide#299] opened 2018-07-10 20:48 UTC
When editing the properties of a file on the Spring Boot App screen, text is not displayed as I type. This problem occurs both in the dark theme and in the classical theme.

![sem titulo](https://user-images.githubusercontent.com/5098914/42536762-55f7788a-8469-11e8-96ff-847b9bc890e8.png)

Ubuntu 16.04
STS 3.9.5

**Comment by kdvolder** [comment] 2018-07-11 16:00
This is a known issue caused by a bug in the Eclipse platform. It works correctly on Ubuntu 18.04 but not on earlier versions. The Eclipse SWT developers decided not to fix this bug and so the recommendation is to upgrade to a newer version of Ubuntu. I know this probably a PITA (I understand because I'm actually in the same boat as you and didn't really want to upgrade to 18.04 just yet). But unfortunately that is the best option.

A second option could be to use STS 3.9.5 on Eclipse 4.7 (the bug is only present in eclipse 4.8). STS 3.9.5 however has not been tested as much on Eclipse 4.7 and its probably a better idea to upgrade Ubuntu instead. 

Here's a link to the bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=533221

There's also a short note in STS 3.9.5 release notes.

Closing this as duplicate of the Eclipse bug.

**Closed by kdvolder** 2018-07-11 16:00 UTC
