### ISSUE TITLE
Problems Extracting Files from Zip Files

### ISSUE THREAD

**Issue by TXMack713** [spring-projects/spring-ide#396] opened 2019-10-29 15:23 UTC
I've run into issues extracting some files from the sts-bundle as I received an error message that some file names cause the file paths to be too long. As a result, I haven't been able to open the software as I continue to get a message that the sts.exe can find the accompanying jar files.
[Files To Copy Over.pdf](https://github.com/spring-projects/spring-ide/files/3784335/Files.To.Copy.Over.pdf)

**Comment by martinlippert** [comment] 2019-10-29 15:42
This is a duplicate of https://github.com/spring-projects/sts4/issues/304. You can either download the latest STS 4.4.1 release for Windows, which comes as a self-extracting JAR file, or use one of the solutions that is mentioned in the referenced issue to extract the ZIP file without running into the path-too-long-issue.

**Closed by martinlippert** 2019-10-29 15:42 UTC

**Comment by TXMack713** [comment] 2019-10-30 01:57
Good evening,

I downloaded STS 4.4.1 as you suggested, but I received this notification
when I went to open the app. Can you advise on what the next steps are?
Thank you for you help with resolving this issue.

[image: image.png]



*Best Regards,Anthony Mack*


*Proverbs 22:29*
*Do you see a man skilled in his work? He will stand before kings; He will
not stand before obscure men.*

**Comment by martinlippert** [comment] 2019-10-30 06:18
@TXMack713 There is no image appearing for me. Please re-upload.

**Comment by martinlippert** [comment] 2019-10-31 13:04
OK, good to hear and thanks for letting us know.
