### ISSUE TITLE
MercurialEclipse

### ISSUE THREAD

**Issue by davidtkaczyk69** [spring-projects/spring-ide#310] opened 2018-08-28 21:23 UTC
Having trouble installing MercurialEclipse direct from marketplace with fresh STS 3.9.5 install (MAC OS).  Using java 8 (1.8.0_181).

Error:

Cannot complete the install because one or more required items could not be found.
Software currently installed: MercurialEclipse 2.5.2.201806082050 (mercurialeclipse.feature.group 2.5.2.201806082050)
         Missing requirement: MercurialEclipse 2.5.2.201806082050 (com.vectrace.MercurialEclipse 2.5.2.201806082050) requires 'osgi.ee; (&(osgi.ee=JavaSE)(version=1.8))' but it could not be found
Cannot satisfy dependency:
From: MercurialEclipse 2.5.2.201806082050 (mercurialeclipse.feature.group 2.5.2.201806082050)
To: org.eclipse.equinox.p2.iu; com.vectrace.MercurialEclipse [2.5.2.201806082050,2.5.2.201806082050]

I've googled a ton and nothing I've tried seems to get this to work.

**Comment by martinlippert** [comment] 2018-09-04 06:37
I think this is a duplicate of: https://github.com/spring-projects/spring-ide/issues/268

**Comment by martinlippert** [comment] 2018-09-04 06:59
Yes, verified, it is the same issue that #268 and the workaround for that is included in the latest STS 3.9.6 builds. You can download a nightly build at: http://dist.springsource.com/snapshot/STS/nightly-distributions.html or wait for the STS 3.9.6 release to be published (shortly after Eclipse 2018-09 is GA, so probably Sep 20).

**Closed by martinlippert** 2018-09-04 06:59 UTC

**Comment by davidtkaczyk69** [comment] 2018-09-04 15:10
Thank you.  Will wait for GA end of Sept...
