### ISSUE TITLE
STS : Error while cloning a Github private  Repository only(Error:git-upload-pack not found)

### ISSUE THREAD

**Issue by kkramireddy** [spring-projects/spring-ide#313] opened 2018-09-06 18:44 UTC
This error occurs only when trying to clone the github respoistory which is private.
org.eclipse.jgit.api.errors.TransportException: https://github.xxxxxx.comm/xxxx/testproj.git: https://github.xxxxxx.comm/xxxx/testproj.git/info/refs?service=git-upload-pack not found
	at org.eclipse.jgit.api.LsRemoteCommand.execute(LsRemoteCommand.java:221)
	at org.eclipse.jgit.api.LsRemoteCommand.call(LsRemoteCommand.java:159)
	at org.eclipse.egit.core.op.ListRemoteOperation.run(ListRemoteOperation.java:100)
	at org.eclipse.egit.ui.internal.clone.SourceBranchPage$8.run(SourceBranchPage.java:341)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)

**Comment by kdvolder** [comment] 2018-09-07 16:32
Do you get a similar problem with a Vanilla Eclipse? The reason I ask is that if this is a bug, it is most likely a bug in Eclipse egit. STS just packages egit from Eclipse. So you'd have to report that bug at Eclipse bugzilla.

BTW: I have used private repositories in the past without too much trouble. That being said I tend to clone repos / projects on the commandline and then just import the projects to Eclipse afterwards as I find the egit ui a bit confusing at times.

Also I'm not totally convinced what you are experiencing is actually a bug. Not saying it isn't a bug, it might very well be, but in your report there's really not enough information to know if / what might have gone wrong. You'd have to include a detailed sequence of steps to reproduce the problem as there are a number of different ways to setup git with your user credentials and a number of different ways/menus/wizards/views you can use in Eclipse to clone repos into your workspace. 

Anyhow... the error suggest that whatever Eclipse component is trying to clone the repo thinks it doesn't exist. I'd expect something like that for a private repo unless Eclipse has your user's credentials somehow (otherwise the private repo would not be visible). So one possible explanation is that your setup is such that Eclipse is trying to clone the repo as a 'anonymous' user.

I'm closing this report as I don't think its an STS bug (it is either something you are doing wrong, or a bug in Eclipse egit).

Don't let that stop you from posting more questions or info here though. We'll do our best to help you. And if you do have some details/evidence this is really a bug in STS, we can allways re-open the ticket.

**Closed by kdvolder** 2018-09-07 16:32 UTC
