### ISSUE TITLE
Alt-Shift-X ... doesn't work correctly

### ISSUE THREAD

**Issue by razorree** [spring-projects/spring-ide#337] opened 2019-01-08 14:25 UTC
When i press Alt-Shift-X, small windows with execution options appear, but it looks like Eclipse/STS is loosing focus completly, i cannot continue by pressing just J or T (to run java or test).
I need to click with my mouse inside STS once !! and then i can press T to run a test.

STS 4.1.0, Ubuntu Mate 16.04
Spring Tool Suite 4 
Version: 4.1.0.RELEASE
Build Id: 201812201400
OS: Linux, v.4.15.0-43-generic, x86_64 / gtk 3.18.9, WebKit 2.20.5
Java version: 1.8.0_181

everything works on previous version:
Spring Tool Suite 
Version: 3.9.6.RELEASE
Build Id: 201809180727
OS: Linux, v.4.15.0-43-generic, x86_64 / gtk 3.18.9
Java version: 1.8.0_181

**Comment by razorree** [comment] 2019-01-08 14:38
Just downloaded and tested,  the same happens with bare Eclipse, so i guess it's a platform issue

Eclipse IDE for Java Developers
Version: 2018-12 (4.10.0)
Build id: 20181214-0600
OS: Linux, v.4.15.0-43-generic, x86_64 / gtk 3.18.9, WebKit 2.20.5
Java version: 1.8.0_181

**Comment by razorree** [comment] 2019-01-08 14:44
https://bugs.eclipse.org/bugs/show_bug.cgi?id=543261

**Comment by martinlippert** [comment] 2019-01-08 14:48
Ok, thanks for double checking and for posting the link to the new bug at Eclipse. Closing this one as a duplicate of the Eclipse bug now.

**Closed by martinlippert** 2019-01-08 14:48 UTC
