### ISSUE TITLE
Autocomplete errors in 3.9.0

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-ide#164] opened 2017-07-13 09:08 UTC
These seem to be more frequent since I upgraded. No freezes yet, but it's very slow and you get a popup (see attached). The error log shows what looks like 2 correlated events:

```
The 'No Prefix Constructor Completiions' proposal computer from the 'org.springsource.ide.eclipse.commons.completions' plug-in did not complete normally. The extension took too long to return from the 'computeCompletionProposals()' operation.
```

(no stack trace).

And

```
Constructor completion proposal timed out
```

<details><summary>stacktrace</summary><p>

```
org.eclipse.core.runtime.OperationCanceledException: Operation cancelled
	at org.eclipse.jdt.internal.core.JavaModelOperation.checkCanceled(JavaModelOperation.java:228)
	at org.eclipse.jdt.internal.core.JavaModelOperation.worked(JavaModelOperation.java:884)
	at org.eclipse.core.runtime.SubMonitor$RootInfo.worked(SubMonitor.java:261)
	at org.eclipse.core.runtime.SubMonitor.done(SubMonitor.java:649)
	at org.eclipse.core.runtime.SubMonitor.cleanupActiveChild(SubMonitor.java:999)
	at org.eclipse.core.runtime.SubMonitor.done(SubMonitor.java:646)
	at org.eclipse.core.runtime.SubMonitor.done(SubMonitor.java:501)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.performConcurrentJob(JobManager.java:264)
	at org.eclipse.jdt.internal.core.hierarchy.IndexBasedHierarchyBuilder.legacySearchAllPossibleSubTypes(IndexBasedHierarchyBuilder.java:650)
	at org.eclipse.jdt.internal.core.hierarchy.IndexBasedHierarchyBuilder.searchAllPossibleSubTypes(IndexBasedHierarchyBuilder.java:488)
	at org.eclipse.jdt.internal.core.hierarchy.IndexBasedHierarchyBuilder.determinePossibleSubTypes(IndexBasedHierarchyBuilder.java:440)
	at org.eclipse.jdt.internal.core.hierarchy.IndexBasedHierarchyBuilder.build(IndexBasedHierarchyBuilder.java:152)
	at org.eclipse.jdt.internal.core.hierarchy.TypeHierarchy.compute(TypeHierarchy.java:319)
	at org.eclipse.jdt.internal.core.hierarchy.TypeHierarchy.refresh(TypeHierarchy.java:1291)
	at org.eclipse.jdt.internal.core.CreateTypeHierarchyOperation.executeOperation(CreateTypeHierarchyOperation.java:90)
	at org.eclipse.jdt.internal.core.JavaModelOperation.run(JavaModelOperation.java:724)
	at org.eclipse.jdt.internal.core.JavaModelOperation.runOperation(JavaModelOperation.java:790)
	at org.eclipse.jdt.internal.core.BinaryType.newTypeHierarchy(BinaryType.java:863)
	at org.eclipse.jdt.internal.core.search.HierarchyScope.initialize(HierarchyScope.java:437)
	at org.eclipse.jdt.internal.core.search.HierarchyScope.encloses(HierarchyScope.java:273)
	at org.eclipse.jdt.core.search.SearchPattern.acceptMatch(SearchPattern.java:328)
	at org.eclipse.jdt.core.search.SearchPattern.findIndexMatches(SearchPattern.java:2348)
	at org.eclipse.jdt.internal.core.search.matching.MatchLocator.findIndexMatches(MatchLocator.java:280)
	at org.eclipse.jdt.internal.core.search.PatternSearchJob.search(PatternSearchJob.java:109)
	at org.eclipse.jdt.internal.core.search.PatternSearchJob.execute(PatternSearchJob.java:65)
	at org.eclipse.jdt.internal.core.search.processing.JobManager.performConcurrentJob(JobManager.java:187)
	at org.eclipse.jdt.internal.core.search.BasicSearchEngine.searchAllConstructorDeclarations(BasicSearchEngine.java:707)
	at org.springsource.ide.eclipse.commons.completions.constructors.ConstructorCompletionEngine.complete(ConstructorCompletionEngine.java:257)
	at org.springsource.ide.eclipse.commons.completions.constructors.ConstructorCompletionEngine.complete(ConstructorCompletionEngine.java:128)
	at org.springsource.ide.eclipse.commons.completions.constructors.NoPrefixConstructorProposalComputer.doComputeCompletionProposals(NoPrefixConstructorProposalComputer.java:144)
	at org.springsource.ide.eclipse.commons.completions.constructors.NoPrefixConstructorProposalComputer.computeCompletionProposals(NoPrefixConstructorProposalComputer.java:71)
	at org.eclipse.jdt.internal.ui.text.java.CompletionProposalComputerDescriptor.computeCompletionProposals(CompletionProposalComputerDescriptor.java:333)
	at org.eclipse.jdt.internal.ui.text.java.CompletionProposalCategory.computeCompletionProposals(CompletionProposalCategory.java:337)
	at org.eclipse.jdt.internal.ui.text.java.ContentAssistProcessor.collectProposals(ContentAssistProcessor.java:331)
	at org.eclipse.jdt.internal.ui.text.java.ContentAssistProcessor.computeCompletionProposals(ContentAssistProcessor.java:288)
	at org.eclipse.jface.text.contentassist.ContentAssistant$3.run(ContentAssistant.java:2007)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.jface.text.contentassist.ContentAssistant.computeCompletionProposals(ContentAssistant.java:2004)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.computeProposals(CompletionProposalPopup.java:560)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.access$7(CompletionProposalPopup.java:555)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup$2.run(CompletionProposalPopup.java:489)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.showProposals(CompletionProposalPopup.java:482)
	at org.eclipse.jface.text.contentassist.ContentAssistant.showPossibleCompletions(ContentAssistant.java:1823)
	at org.eclipse.jdt.internal.ui.javaeditor.CompilationUnitEditor$AdaptedSourceViewer.doOperation(CompilationUnitEditor.java:184)
	at org.eclipse.ui.texteditor.ContentAssistAction$1.run(ContentAssistAction.java:84)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.ui.texteditor.ContentAssistAction.run(ContentAssistAction.java:81)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
	at org.eclipse.jface.commands.ActionHandler.execute(ActionHandler.java:118)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:92)
	at sun.reflect.GeneratedMethodAccessor333.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:305)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:239)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:494)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.executeCommand(KeyBindingDispatcher.java:285)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.press(KeyBindingDispatcher.java:506)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.processKeyEvent(KeyBindingDispatcher.java:557)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.filterKeySequenceBindings(KeyBindingDispatcher.java:377)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.access$0(KeyBindingDispatcher.java:323)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher$KeyDownFilter.handleEvent(KeyBindingDispatcher.java:85)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1577)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1347)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1374)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1357)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1386)
	at org.eclipse.swt.widgets.Widget.gtk_key_press_event(Widget.java:768)
	at org.eclipse.swt.widgets.Control.gtk_key_press_event(Control.java:3526)
	at org.eclipse.swt.widgets.Link.gtk_key_press_event(Link.java:422)
	at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:1976)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:6168)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5512)
	at org.eclipse.swt.internal.gtk.OS._gtk_main_do_event(Native Method)
	at org.eclipse.swt.internal.gtk.OS.gtk_main_do_event(OS.java:9251)
	at org.eclipse.swt.widgets.Display.eventProc(Display.java:1252)
	at org.eclipse.swt.internal.gtk.OS._g_main_context_iteration(Native Method)
	at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(OS.java:2110)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4105)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:818)
	at org.eclipse.jface.window.Window.open(Window.java:794)
	at org.eclipse.jface.dialogs.MessageDialog.open(MessageDialog.java:396)
	at org.eclipse.jdt.internal.ui.text.java.CompletionProposalComputerRegistry.informUser(CompletionProposalComputerRegistry.java:465)
	at org.eclipse.jdt.internal.ui.text.java.CompletionProposalComputerDescriptor.stopMeter(CompletionProposalComputerDescriptor.java:501)
	at org.eclipse.jdt.internal.ui.text.java.CompletionProposalComputerDescriptor.computeCompletionProposals(CompletionProposalComputerDescriptor.java:334)
	at org.eclipse.jdt.internal.ui.text.java.CompletionProposalCategory.computeCompletionProposals(CompletionProposalCategory.java:337)
	at org.eclipse.jdt.internal.ui.text.java.ContentAssistProcessor.collectProposals(ContentAssistProcessor.java:331)
	at org.eclipse.jdt.internal.ui.text.java.ContentAssistProcessor.computeCompletionProposals(ContentAssistProcessor.java:288)
	at org.eclipse.jface.text.contentassist.ContentAssistant$3.run(ContentAssistant.java:2007)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.jface.text.contentassist.ContentAssistant.computeCompletionProposals(ContentAssistant.java:2004)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.computeProposals(CompletionProposalPopup.java:560)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.access$7(CompletionProposalPopup.java:555)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup$2.run(CompletionProposalPopup.java:489)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.jface.text.contentassist.CompletionProposalPopup.showProposals(CompletionProposalPopup.java:482)
	at org.eclipse.jface.text.contentassist.ContentAssistant.showPossibleCompletions(ContentAssistant.java:1823)
	at org.eclipse.jdt.internal.ui.javaeditor.CompilationUnitEditor$AdaptedSourceViewer.doOperation(CompilationUnitEditor.java:184)
	at org.eclipse.ui.texteditor.ContentAssistAction$1.run(ContentAssistAction.java:84)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
	at org.eclipse.ui.texteditor.ContentAssistAction.run(ContentAssistAction.java:81)
	at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
	at org.eclipse.jface.commands.ActionHandler.execute(ActionHandler.java:118)
	at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:92)
	at sun.reflect.GeneratedMethodAccessor333.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:55)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:305)
	at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:239)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:132)
	at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:152)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:494)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:210)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.executeCommand(KeyBindingDispatcher.java:285)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.press(KeyBindingDispatcher.java:506)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.processKeyEvent(KeyBindingDispatcher.java:557)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.filterKeySequenceBindings(KeyBindingDispatcher.java:377)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher.access$0(KeyBindingDispatcher.java:323)
	at org.eclipse.e4.ui.bindings.keys.KeyBindingDispatcher$KeyDownFilter.handleEvent(KeyBindingDispatcher.java:85)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.filterEvent(Display.java:1577)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1347)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1374)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1357)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1386)
	at org.eclipse.swt.widgets.Widget.gtk_key_press_event(Widget.java:768)
	at org.eclipse.swt.widgets.Control.gtk_key_press_event(Control.java:3526)
	at org.eclipse.swt.widgets.Composite.gtk_key_press_event(Composite.java:785)
	at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:1976)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:6168)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5512)
	at org.eclipse.swt.internal.gtk.OS._gtk_main_do_event(Native Method)
	at org.eclipse.swt.internal.gtk.OS.gtk_main_do_event(OS.java:9251)
	at org.eclipse.swt.widgets.Display.eventProc(Display.java:1252)
	at org.eclipse.swt.internal.gtk.OS._g_main_context_iteration(Native Method)
	at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(OS.java:2110)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4105)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1044)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1472)
```

</p></details>

**Comment by dsyer** [comment] 2017-07-13 09:08
![2017-07-13-100001_1366x768_scrot](https://user-images.githubusercontent.com/124075/28158921-38600928-67b3-11e7-86a2-28fef7ccb828.png)

**Comment by martinlippert** [comment] 2017-07-13 09:23
As a workaround, does it work better if you disable the mentioned category via the content-assist preferences?

**Comment by dsyer** [comment] 2017-07-13 09:57
Thanks, that seems to improve things (so far at least).

**Comment by gayanper** [comment] 2017-08-25 05:15
Disable the content assistance category didn't help. Still the error message popups for me.

**Comment by martinlippert** [comment] 2017-08-25 06:33
@gayanper can you post the stack trace from your error message (maybe from the Error Log view)? Would be interesting to see what exactly goes wrong there.

**Comment by gayanper** [comment] 2017-08-27 15:53
@martinlippert Seems like a clean restart to eclipse solved it after following the workaround. Sorry that i wasted time of yours :(

**Comment by martinlippert** [comment] 2017-08-28 07:51
No problem at all and glad to hear you got it working. In case you've seen a different error message than the one mentioned above, please let us know and post the stack trace.

**Comment by gayanper** [comment] 2017-09-04 15:25
Sorry i have tested in my wrong eclipse installation. I tried it the installation i have Spring Tools installed and i get the following message in error log and there is no stack trace available.
"The 'No Prefix Constructor Completiions' proposal computer from the 'org.springsource.ide.eclipse.commons.completions' plug-in did not complete normally. The extension violated the API contract of the 'computeContextInformation()' operation."

**Comment by martinlippert** [comment] 2017-09-04 15:29
@gayanper and disabling the category in the content-assist preferences does NOT work around this for you?

**Comment by gayanper** [comment] 2017-09-09 16:01
@martinlippert No the workaround didn't worked out for me.

**Comment by martinlippert** [comment] 2017-09-11 07:36
Can you share a screenshot of your settings from `Preferences -> Java -> Editor -> Content-Assist -> Advanced` ? I would like to see that is active there.

Also does this problem happen on every project? Or just specific ones? Each time or just sometimes? And can you maybe share a project that causes this?

**Comment by gayanper** [comment] 2017-09-11 16:06
![contentasist](https://user-images.githubusercontent.com/7471994/30284497-b6105896-9738-11e7-98b4-a543108460a4.png)

One thing i notice when i tried on a clean workspace, as soon as i change the preference and applies the problem goes away. But it is back as soon as i restart eclipse. You can see the preference how it looks like even after restart.

**Comment by spring-issuemaster** [comment] 2017-09-13 21:42
(comment in Pivotal Tracker added by Nieraj Singh:) 

I am able to reproduce the issue.

In a Java class, do the following:

List<String> l = new <Ctrl-Space>

When invoking CA, I get the attached error dialogue.

**Comment by spring-issuemaster** [comment] 2017-09-13 22:33
(comment in Pivotal Tracker added by Nieraj Singh:) 

This issue appears to happen due to short timeout for the No Prefix Constructor completion related to a fix for this bug:

https://www.pivotaltracker.com/n/projects/1346850/stories/117072141

If I increase the timeout, I no longer get the dialogue and stack trace.

But the more important question is if we still need this proposal.

When I disable our proposal, and rely entirely on JDT, I get the same list of proposals in the same order.

Do we really need our own "hack" proposal, or should we remove it and rely on JDT?

**Comment by spring-issuemaster** [comment] 2017-09-15 18:09
(comment in Pivotal Tracker added by Nieraj Singh:) 

One possible idea to avoid this, is to cache the results of the proposal, which would happen in the background asynchronously.

Our proposal computer would then return immediately with results from the cache, thus avoiding any timeouts and preventing the JDT error dialogue from popping up , and we'd keep the cache up to date every time CA is launched again.

The drawback with this is the very first time CA is invoked, it may show no results, but subsequent invocations will contain more results.

If we want this, I would need about  a day more to implement this, or we can defer this  to post 3.9.1, since this issue is not always reproducible.

**Comment by spring-issuemaster** [comment] 2017-09-19 03:17
(comment in Pivotal Tracker added by Nieraj Singh:) 

The "no prefix" constructor search is now performed asynchronously using a Flux/Reactor-based JDT search. The results are read from a cache so it should no longer be blocking the UI thread, and therefore not causing timeouts anymore.

However, this has not been thoroughly tested.  Should test this to ensure no regressions introduced.

**Closed** 2017-09-19 08:17 UTC
Labels: accepted
