### ISSUE TITLE
CF STS4 4.3.1.RELEASE Push failed java.lang.ClassNotFoundException: com.sun.org.apache.xml.internal.resolver.CatalogManager

### ISSUE THREAD

**Issue by jurevert** [spring-projects/spring-ide#387] opened 2019-07-17 10:10 UTC
Deployment using Drag&Drop of a Spring Boot App (2.1.6.RELEASE) in 'Boot Dashboard' STS view and using Java 11, failed with error **Caused by: java.lang.ClassNotFoundException: com.sun.org.apache.xml.internal.resolver.CatalogManager** :
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'w000479.v1': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: SDFW-CON-005: Could not create WebServiceClient  'class com.afklm.soa.stubs.w000479.v1.ProvideUserRightsAccessV10_Service', URL: 'jar:file:/home/vcap/app/lib/w000479-v01-0.jar!/META-INF/wsdl/w000479-v01/w000479-v01-policy.wsdl'
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1778) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:826) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877) ~[spring-context-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549) ~[spring-context-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:742) ~[spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:389) ~[spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:311) ~[spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1213) ~[spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1202) ~[spring-boot-2.1.6.RELEASE.jar!/:2.1.6.RELEASE]
	at com.afklm.akevents.AkeventsSsApplication.main(AkeventsSsApplication.java:10) ~[app/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53) ~[app/:na]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
Caused by: java.lang.IllegalArgumentException: SDFW-CON-005: Could not create WebServiceClient  'class com.afklm.soa.stubs.w000479.v1.ProvideUserRightsAccessV10_Service', URL: 'jar:file:/home/vcap/app/lib/w000479-v01-0.jar!/META-INF/wsdl/w000479-v01/w000479-v01-policy.wsdl'
	at com.afklm.soa.spring.consumer.ServiceCreator.createService(ServiceCreator.java:43) ~[jaxws-consumer-3.0.3.jar!/:3.0.3#40a3e42]
	at com.afklm.soa.spring.consumer.WebServiceConsumer.afterPropertiesSet(WebServiceConsumer.java:230) ~[jaxws-consumer-3.0.3.jar!/:3.0.3#40a3e42]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1837) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1774) ~[spring-beans-5.1.8.RELEASE.jar!/:5.1.8.RELEASE]
	... 22 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source) ~[na:na]
	at com.afklm.soa.spring.consumer.ServiceCreator.createService(ServiceCreator.java:40) ~[jaxws-consumer-3.0.3.jar!/:3.0.3#40a3e42]
	... 25 common frames omitted
Caused by: java.lang.NoClassDefFoundError: com/sun/org/apache/xml/internal/resolver/CatalogManager
	at com.sun.xml.ws.util.xml.XmlUtil.createDefaultCatalogResolver(XmlUtil.java:296) ~[webservices-rt-2.4.3.jar!/:2.4.3]
	at com.sun.xml.ws.client.WSServiceDelegate.createCatalogResolver(WSServiceDelegate.java:348) ~[webservices-rt-2.4.3.jar!/:2.4.3]
	at com.sun.xml.ws.client.WSServiceDelegate.parseWSDL(WSServiceDelegate.java:334) ~[webservices-rt-2.4.3.jar!/:2.4.3]
	at com.sun.xml.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:292) ~[webservices-rt-2.4.3.jar!/:2.4.3]
	at com.sun.xml.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:201) ~[webservices-rt-2.4.3.jar!/:2.4.3]
	at com.sun.xml.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:182) ~[webservices-rt-2.4.3.jar!/:2.4.3]
	at com.sun.xml.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:178) ~[webservices-rt-2.4.3.jar!/:2.4.3]
	at com.sun.xml.ws.spi.ProviderImpl.createServiceDelegate(ProviderImpl.java:89) ~[webservices-rt-2.4.3.jar!/:2.4.3]
	at javax.xml.ws.Service.<init>(Service.java:82) ~[webservices-api-2.4.3.jar!/:2.4.3]
	at com.afklm.soa.stubs.w000479.v1.ProvideUserRightsAccessV10_Service.<init>(ProvideUserRightsAccessV10_Service.java:42) ~[w000479-v01-0.jar!/:0#a2702a59bc2c8277cc0b5103b44a9fbceec56238]
	... 30 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.sun.org.apache.xml.internal.resolver.CatalogManager
	at java.base/java.net.URLClassLoader.findClass(Unknown Source) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[na:na]
	at org.springframework.boot.loader.LaunchedURLClassLoader.doLoadClass(LaunchedURLClassLoader.java:170) ~[app/:na]
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:136) ~[app/:na]
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source) ~[na:na]
	... 40 common frames omitted
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
	at java.base/java.lang.Thread.run(Unknown Source)

```
Deployment using directly CF CLI is working fine.
Thanks for help,
Julien

**Comment by spring-issuemaster** [comment] 2019-07-18 17:06
(comment in Pivotal Tracker added by Alex Boyko:) 

Looks like i need a very specific project to be able to reproduce it... I'll try to create a project with com.sun.org.apache.xml.internal.resolver.CatalogManager, but it'd be great if a sample project could be attached to this issue...
Overall seems like some classpath issue between JDK 11 and 8... maybe a module in JDK 11 hasn't been included in the classpath?

**Comment by kdvolder** [comment] 2019-07-23 17:00
I suspect there's some discrepancy between packaging/classpath for the app deployed with drag-and-drop versus building and deplying on the CLI. Without more details (a sample project to reproduce the issue would be best), there is really not much we can do to narrow this down. The projects that we have tried ourselves do not trigger this problem.

I am closing this ticket now as "Canot Reproduce". 

But we can re-open it and take a closer look if you can attach a sample project (or precise instructions on how to set one up for ourselves).

**Closed by kdvolder** 2019-07-23 17:00 UTC

**Comment by jurevert** [comment] 2019-07-24 07:22
Thanks for your answer.
Not so easy to give you a sample since it's a quite big project with multiples internals components/dependencies. Will still use STS 3.x for now (working fine with it.).
If I had time to simplify project and give you a sample ; I will do this.
At least the error is logged here now if someone else face it.
Julie,

**Comment by martinlippert** [comment] 2019-07-29 09:03
@jurevert Hey Julien, thanks for the update and sorry for the inconvenience with this. Would be really great if you could find the time to track this down to a project that you could share with us in order to reproduce this. Another option would be to analyze the deployed project and compare that with the one deployed via STS 3.9.x so see what the difference is (e.g. by using the cf CLI to browse the deployed files of your app). Maybe those results could provide additional ideas how to reproduce this on our end.
