### ISSUE TITLE
STS 3 3.9.9 can not display Spring Integration XML files any longer

### ISSUE THREAD

**Issue by realwuffi** [spring-projects/spring-ide#384] opened 2019-06-26 14:01 UTC
In version 3.9.8 I could open a Spring Integration XML file without any problems using the Spring Config Editor.
After the update to STS 3.9.9 the integration graph could not be displayed any longer.

I'm using Eclipse 2019-03, running on a JDK 8.

**Comment by martinlippert** [comment] 2019-07-08 07:43
Using a simple example running on top of a distribution download of STS 3.9.9 (on top of Eclipse 2019-06), I could not reproduce the issue. I imported the "Integrating Data" guide into my workspace and opened the `integration.xml` file in the editor. The tab for the "integration graph" displays the graph just fine.

Can you attach a sample project that could help us to reproduce the issue? That would be great. And does the `integration graph` tab appears, but is empty or does the tab not appear at all? Is there anything in the `Error Log` view that could be related to this problem?

**Comment by martinlippert** [comment] 2019-07-08 07:44
(oh, and sorry for the late reply, appreciate for that)

**Comment by realwuffi** [comment] 2019-09-11 09:09
Hi Martin,
sorry for the really late reply here, I was just very busy and after that on holidays :-)

I tried Eclipse 2019-03 (which we use in our company at the moment) and updated to the 3.9.9 version (also all other available updates for Eclipse)
Attached you will find the Logfile, which has loads of exceptions.

The whole integartion tab is missing in the editor. I'm not sure if the BeansMoveRefactorAction is the root cause, which seens not to match the Eclipse API (no JavaMoveProcessor available)

Does that help?
Thanks
Wolfgang

**Comment by realwuffi** [comment] 2019-09-17 12:46
Hello Martin,

thanks for the information.
It seems like I can’t find a solution for that. Every time I try to install the updates,
Eclipse calculates a solution which retrieves loads of updates for other plugins as well.

And after that the installation is broken producing loads of errors in the log.
Unfortunately I can’t spend any more time on that issue.
It would be okay for me if you close this issue.

Thanks
Wolfgang

Von: Martin Lippert <notifications@github.com>
Gesendet: Freitag, 13. September 2019 08:52
An: spring-projects/spring-ide <spring-ide@noreply.github.com>
Cc: Pausch Wolfgang <Wolfgang.Pausch@tgw-group.com>; Author <author@noreply.github.com>
Betreff: [EXT] Re: [spring-projects/spring-ide] STS 3 3.9.9 can not display Spring Integration XML files any longer (#384)


Hey Wolfgang, thanks for the error log, that is indeed super helpful.

Unfortunately it looks like there are some serious compatibility issues happening under the hood of your install, probably caused by a combination of various third-party plugins installed and updated over time, so your installation seems to be more or less broken at the moment.

I would recommend to undo the latest updates/installs, you can do that via the About dialog, and then select the Installation Details, then the Installation History tab. There you can select a specific state and revert back to that.

In order to investigate the details of this issue, I would try to reproduce this by installing the same than you did, so it would be great if you could tell me what you installed (from which update dates) if possible.

I also remember us fixing some issues around javax.xml.bind wiring issues, so you could also try to install the CI build from here: https://dist.springsource.com/snapshot/TOOLS/nightly/e4.11 - in case you are still at Eclipse 2019-03. This CI build is already a bit outdated, since we don't run the CI builds for Eclipse 2019-03 anymore, but I could resurrect them, if that would help you.

**Comment by martinlippert** [comment] 2019-09-23 17:15
Hey Wolfgang, thanks for the update and sure, we can close the issue. But I would love to find out what is going wrong under the hood nevertheless... :-) Can you snapshot the list of updates that show up when you do the "Check for Updates" that result in the bad and broken state? Maybe that list could reveal some interesting details and hints how to reproduce this locally. That would be awesome.

**Closed by martinlippert** 2019-09-23 17:15 UTC

**Comment by realwuffi** [comment] 2019-09-24 09:46
Hi Martin,

thanks for the support.
I gave it another try, you will find an Excel file attached to this mail.

The first sheet show the configuration an log messages before the update,
The second sheet shows the suggested updates and the log messages after the update.

It doesn’t matter if I use Java 8 or Java 11 to start Eclipse.
Looks like a “bundle” problem, as the enterprise api has been removed from the JDK
and has to be provided by extra JAR files.

I don’t have that much experience with this matter yet, so I can’t really tell what the problem is here.

What I realized as well is, that when I start Eclipse with Java 8, the javax.xml.bind_2.2.0.v201105210648.jar
should not exist in the “plugins” directory. This will lead to a crash of the Spring Config Editor (Integration View) as well.
(I guess this is because the runtime will find two JAXBContext on the classpath or so)

I hope you can find something and thanks for your support.

Cheers
Wolfgang

Von: Martin Lippert <notifications@github.com>
Gesendet: Montag, 23. September 2019 19:15
An: spring-projects/spring-ide <spring-ide@noreply.github.com>
Cc: Pausch Wolfgang <Wolfgang.Pausch@tgw-group.com>; Author <author@noreply.github.com>
Betreff: [EXT] Re: [spring-projects/spring-ide] STS 3 3.9.9 can not display Spring Integration XML files any longer (#384)


Hey Wolfgang, thanks for the update and sure, we can close the issue. But I would love to find out what is going wrong under the hood nevertheless... :-) Can you snapshot the list of updates that show up when you do the "Check for Updates" that result in the bad and broken state? Maybe that list could reveal some interesting details and hints how to reproduce this locally. That would be awesome.

**Comment by martinlippert** [comment] 2020-04-02 09:33
I finally double checked this again with the latest STS 3.9.12 release on Eclipse 2020-03 and it seems to work (tried spring-integration-samples projects), the Spring Config Editor opens just fine and you can select the integration-graph tab, too.

The underlying issue above might be caused by additional bundles being installed or old installations being updated over time (or a combination of both). I tried a fresh STS 3.9.12 install and that works, so in case you come across this again, please let me know what else you installed into your STS 3.9.12 install, so that I can maybe produce this here.

In addition to this I would still highly recommend to switch to the new Spring Tools 4 sometime soon. It doesn't contain a graphical Spring Integration visualization yet, but we are working on that already and have something to release soon. So stay tuned for that.

**Comment by realwuffi** [comment] 2020-04-02 11:26
Hi Martin,
Sorry, I totally forgot to reply to this topic.
In the meantime I found the issue as well. It was a different bundle not supported by Eclipse any longer which caused the problem during startup of Eclipse. So no issue here.

As we rely on that graphical editor, we can't switch yet, but as soon as it is contained in version 4 of the tools, we will give it a try!

Cheers
Wolfgang

**Comment by martinlippert** [comment] 2020-04-02 13:53
Hey Wolfgang! I would like to hear more about your usage of the graphical representation of the Spring Integration files and the use cases, so understanding more about the why and when you use it and for what purpose.

As a reference, this issue contains a discussion about the new Spring Integration graph visualizer, which works slightly different than the old one: https://github.com/spring-projects/sts4/issues/167 - it also contains a short how-to for the new implementation for trying it out. I wonder what you think about that. I think the new graph visualizer is quite nice, but it works on live data while running the app (which you can easily achieve even for, lets say, "non-real" projects, as Gary described in the comments).
