### ISSUE TITLE
spring nature is not added on maven project import for project with spring-boot-starter-parent

### ISSUE THREAD

**Issue by cforce** [spring-projects/spring-ide#141] opened 2017-05-09 18:22 UTC
STS 3.8.4

Although i have "spring-boot-starter-parent" downstram in my <parent> pom "inheritance" of my project being imported, STS does not automatically add the spring nature on "import existing maven project". Therfore the project also does not show up in spring explorer and spring boot dashboard. From what i remember that worked once and should work out of the box, based on m2e detection of spring boot deps, shouldn't it?

As i have about 100 microservices being manged in a git project via submodules, it would be a hell to tweak every project by mouse and/or manually edit .project files. In fact we don't want to check in .project files also.

**Comment by kdvolder** [comment] 2017-05-09 18:44
>  once and should work out of the box, based on m2e detection of spring boot deps, shouldn't it?

Yes. 

Do you have a sample project available. It works for the projects I've tried. So I'll need your specific example to debug the nature of the problem.

**Comment by Silkroute-Xenon** [comment] 2018-03-06 08:17
Hi,
Cut and paste your pom.xml file contents. The project will be updated with necessary spring elements.

**Comment by kdvolder** [comment] 2018-03-08 17:44
I'm closing this issue as the descriptions are not specific enough to reproduce or diagnose a problem. 
We can reopen it if a more concrete description of what doesn't work. 

For example, there several different ways / wizards that a user can get maven projects into their workspace. So try and describe precise steps of what you do. A sample project to import that demonstrates the problem is also very welcome, but it is a bonus.

We try to do our best with whatever information you provide, but what information we have right now simply isn't enough to know what is going wrong for you.

**Closed by kdvolder** 2018-03-08 17:44 UTC
