### ISSUE TITLE
STS 4.0.0 comment/uncomment hotkey not working

### ISSUE THREAD

**Issue by Padmahas** [spring-projects/spring-ide#373] opened 2019-04-02 06:54 UTC
Hello,

Hotkey for commenting and uncommenting not working in Spring properties editor.
It applies to both single line comment "CTRL + /" and
multi line comment "CTRL + SHIFT + /".

Please provide this feature as it is most use full when dealing with multi lines.

Thank you.

**Comment by martinlippert** [comment] 2019-04-02 08:47
I think this is a duplicate of https://github.com/spring-projects/sts4/issues/100. I tested this again using the my STS 4.2.0 for Eclipse install and the toggle comment shortcut works for single- and multiple lines. However, on my macOS version is it `Shift-Cmd-C` nothing with `/`.

**Closed by martinlippert** 2019-04-02 08:47 UTC
