### ISSUE TITLE
Fast Startup Issue for Spring Boot application.

### ISSUE THREAD

**Issue by vinodjavvadi** [spring-projects/spring-ide#172] opened 2017-07-18 18:32 UTC
Fast Startup Option is casuing -noverify to get appended to the arguments causing a new value.

Example:
My VM Arguments has the following arguments.
-Dserver.port=0 
-XX:+AggressiveOpts

When I try to run my spring boot application, I get the following:
 
Unrecognized VM option 'AggressiveOpts-noverify'
Did you mean '(+/-)AggressiveOpts'?

========================================================
So you can see that -noverify is getting appended to the last vm argument with out any space. Please try to add the arguments with space so that the existing arguments are not messed up.

**Comment by BoykoAlex** [comment] 2017-07-18 18:38
This is duplicate of https://github.com/spring-projects/spring-ide/issues/159

**Comment by vinodjavvadi** [comment] 2017-07-18 18:39
Thank you for the reply.

**Comment by BoykoAlex** [comment] 2017-07-18 18:42
Which is resolved already. Please disable `Fast Startup` in the `Spring -> Boot` preferences for now by making VM options just an empty string.

**Comment by vinodjavvadi** [comment] 2017-07-18 18:45
Got it thank you.

**Closed** 2017-07-18 18:53 UTC
