### ISSUE TITLE
ClassCastException when Importing a Spring Getting Started Project

### ISSUE THREAD

**Issue by phoppe9966** [spring-projects/spring-ide#370] opened 2019-03-27 07:19 UTC
I use Eclipse 4.8 Photon with the Spring Tools 3 Addon 3.9.7.RELEASE installed.
I try to Import a Spring Getting Started Project with:

File -> New -> Other -> Spring Boot -> Import Spring Getting Started Content

Then I get the following Error:

The selected wizard could not be started.
Plug-in "org.springframework.ide.eclipse.boot.wizard" was unable to instantiate class "org.springframework.ide.eclipse.boot.wizard.guides.GSImportWizard".
ClassCastException: attempting to castbundleresource://1621.fwk1437454238:7/javax/ws/rs/client/ClientBuilder.class to bundleresource://1614.fwk1437454238/javax/ws/rs/client/ClientBuilder.class

What can I do?

**Comment by martinlippert** [comment] 2019-03-27 12:40
I guess this is a duplicate of this:
https://github.com/spring-projects/sts4/issues/202

We just released 3.9.8, so please update to that release (or start with a fresh STS 3.9.8 distribution), that should solve the issue.

**Comment by martinlippert** [comment] 2019-03-27 12:41
I should also mention that updating to STS 3.9.8 would also mean to update at least to Eclipse 2018-09 (Eclipse 4.9).

**Closed by martinlippert** 2019-03-27 12:40 UTC

**Comment by phoppe9966** [comment] 2019-03-27 14:46
Thank you Martin.
I will change to Eclipse 4.9 and install the new Spring Tools Plugin 3.9.8.
