### ISSUE TITLE
Tags in yaml files with dollar signs throw IllegalGroupReference (3.9.8.201903260659-RELEASE)

### ISSUE THREAD

**Issue by jmax01** [spring-projects/spring-ide#376] opened 2019-04-29 16:23 UTC
This line throws  `java.lang.IllegalArgumentException: Illegal group reference` whenever an edit is applied.
``` yaml
logging.level.org.springframework.kafka.listener.[KafkaMessageListenerContainer$ListenerConsumer]: INFO
```
```
java.lang.IllegalArgumentException: Illegal group reference
	at java.util.regex.Matcher.appendReplacement(Matcher.java:857)
	at org.springsource.ide.eclipse.commons.core.util.StringUtil.camelCaseToHyphens(StringUtil.java:66)
	at org.springframework.ide.eclipse.boot.properties.editor.yaml.reconcile.ApplicationYamlASTReconciler.reconcile(ApplicationYamlASTReconciler.java:149)
	at org.springframework.ide.eclipse.boot.properties.editor.yaml.reconcile.ApplicationYamlASTReconciler.reconcile(ApplicationYamlASTReconciler.java:97)
	at org.springframework.ide.eclipse.boot.properties.editor.yaml.reconcile.ApplicationYamlASTReconciler.reconcile(ApplicationYamlASTReconciler.java:83)
	at org.springframework.ide.eclipse.boot.properties.editor.yaml.reconcile.ApplicationYamlASTReconciler.reconcile(ApplicationYamlASTReconciler.java:74)
	at org.springframework.ide.eclipse.editor.support.yaml.reconcile.YamlReconcileEngine.reconcile(YamlReconcileEngine.java:43)
	at org.springframework.ide.eclipse.editor.support.reconcile.ReconcileStrategy.reconcile(ReconcileStrategy.java:88)
	at org.eclipse.jface.text.reconciler.MonoReconciler.process(MonoReconciler.java:76)
	at org.eclipse.jface.text.reconciler.AbstractReconciler$BackgroundThread.run(AbstractReconciler.java:210)

```

**Comment by kdvolder** [comment] 2019-04-29 16:32
Can you please provide a more detailed example. It's easier than us trying to guess/create it ourselves based on your description. This seems to be an error from the reconciler. So pasting exact content of the editor should be good enough to reproduce it.

**Comment by jmax01** [comment] 2019-04-29 21:26
There is not really much more to add
1. Open Error Log View 
2. Create an application-test.yml file.
3. Add this line to the file:
    `logging.level.org.springframework.kafka.listener.[KafkaMessageListenerContainer$ListenerConsumer]: INFO`
4. An error similar to this one should appear in the Error Log view:
```
IllegalArgumentException: Illegal group reference

java.lang.IllegalArgumentException: Illegal group reference
	at java.util.regex.Matcher.appendReplacement(Matcher.java:857)
	at org.springsource.ide.eclipse.commons.core.util.StringUtil.camelCaseToHyphens(StringUtil.java:66)
	at org.springframework.ide.eclipse.boot.properties.editor.yaml.reconcile.ApplicationYamlASTReconciler.reconcile(ApplicationYamlASTReconciler.java:149)
	at org.springframework.ide.eclipse.boot.properties.editor.yaml.reconcile.ApplicationYamlASTReconciler.reconcile(ApplicationYamlASTReconciler.java:97)
	at org.springframework.ide.eclipse.boot.properties.editor.yaml.reconcile.ApplicationYamlASTReconciler.reconcile(ApplicationYamlASTReconciler.java:83)
	at org.springframework.ide.eclipse.boot.properties.editor.yaml.reconcile.ApplicationYamlASTReconciler.reconcile(ApplicationYamlASTReconciler.java:74)
	at org.springframework.ide.eclipse.editor.support.yaml.reconcile.YamlReconcileEngine.reconcile(YamlReconcileEngine.java:43)
	at org.springframework.ide.eclipse.editor.support.reconcile.ReconcileStrategy.reconcile(ReconcileStrategy.java:88)
	at org.eclipse.jface.text.reconciler.MonoReconciler.process(MonoReconciler.java:76)
	at org.eclipse.jface.text.reconciler.AbstractReconciler$BackgroundThread.run(AbstractReconciler.java:210)
``

**Comment by kdvolder** [comment] 2019-04-30 15:30
Thanks for the example. It doesn't seem like much maybe, but this is exactly what I need:

```
logging.level.org.springframework.kafka.listener.[KafkaMessageListenerContainer$ListenerConsumer]: INFO
```

The saying is that a 'picture is worth a thousand words'. In our world however I'd say that it should rathe be  'an example is worth a thousand words' :-)

**Comment by kdvolder** [comment] 2019-04-30 16:49
Github auto-closed this issue because I pushed a fix to STS 4 repo... however, still need to fix STS 3 legacy editor as well. So re-opening this.

**Closed** 2019-04-30 16:54 UTC
Labels: started
