### ISSUE TITLE
sts caching

### ISSUE THREAD

**Issue by wangzezz** [spring-projects/spring-ide#309] opened 2018-08-27 05:09 UTC
I created a springboot project A， STS always recorded my project A's messages，but when I creating project B，I find that B's pom.xml is the same as A, how can I solve this problem

**Comment by kdvolder** [comment] 2018-08-27 19:04
You'll have to elaborate more precisely what it is you are doing. Just reading your message I have no idea what the problem is, what causes it, or how to solve it.

So perhaps can do a bit more step by step. Something like a) do this, b) do that, c) observe that X happens, but that is wrong because it should do Y. In other words try to make it like a little 'recipe' that we can follow so that we can reproduce and see the problem ourselves. Then... maybe we can figure out how to fix or work around it.

**Comment by kdvolder** [comment] 2018-08-27 19:05
I'm closing this ticket for now because insufficient details to do anything. Please feel free to re-open it after adding more details.

**Closed by kdvolder** 2018-08-27 19:05 UTC

**Comment by wangzezz** [comment] 2018-08-28 10:32
thanks for responsed me this question
a) create a new springboot project A 
b) config A's pom.xml , eg: add dependency of spring-cloud
c) create anothor springboot project B
d) I find A's pom.xml Nearly equals to B' pom.xml
I don't konw how could I solve this problem , so I only can ask help from you , thanks for your help

**Comment by wangzezz** [comment] 2018-08-29 01:30
the problem is that I found two project's pom.xml is the same，but project A is configed，project B is a new one , I want to know the reason that why a new project's pom.xml is the same as a previous one

**Comment by kdvolder** [comment] 2018-08-29 17:36
I followed the steps you listed and my two projects ended up with different poms. So I don't know why yours are the same. I'm also not really sure what you bean by 'project A is configured'.

**Comment by wangzezz** [comment] 2018-08-30 01:10
OK, thanks
