### ISSUE TITLE
Extract to local variable broken

### ISSUE THREAD

**Issue by dsyer** [spring-projects/spring-ide#89] opened 2017-01-04 10:57 UTC
With this code:

```java
result.put(key,
    wrapSupplier((Supplier<Flux<?>>) suppliers.get(key), mapper));
```

if I select the `(Supplier<Flux<?>>) suppliers.get(key)` and CTRL-SHIFT-L (Extract Local Variable) it screws up the syntax and then cannot compile the result:

```java
Supplier< supplier = (Supplier<Flux<?>>) suppliers.get(key);
result.put(key,
     wrapSupplier(supplier, mapper));
```

I think this was working in 3.8.0 (but not in 3.8.3).

**Comment by martinlippert** [comment] 2017-01-04 15:30
This seems to work for me with a fresh STS 3.8.3 install (as well as plain Eclipse Oxygen M3), but maybe I am using a slightly different code context (mocked up the surroundings). Can you share the project with me to try things out in the same setting?

**Comment by dsyer** [comment] 2017-01-05 08:57
I was working here: https://github.com/dsyer/spring-cloud-function/blob/feature/catalog/spring-cloud-function-context/src/main/java/org/springframework/cloud/function/context/ContextFunctionCatalogAutoConfiguration.java. I have 3.8.3 with Groovy tooling added from the STS dashboard, plus YK and JDepend.

**Comment by spring-issuemaster** [comment] 2017-01-05 14:18
(comment in Pivotal Tracker added by Martin Lippert:) 

Thanks for the additional details. Seems like Groovy-Eclipse is the root cause of this error. The refactoring works just fine with a pure STS 3.8.3, but fails with exactly what you described when Groovy-Eclipse is installed. Will add @andyclement to the discussion, maybe he can help here.

**Comment by spring-issuemaster** [comment] 2017-01-05 16:44
(comment in Pivotal Tracker added by Andy Clement:) 

Not sure precisely which version you have Dave but could be worth updating to the latest greclipse snapshot: http://dist.springsource.org/snapshot/GRECLIPSE/e4.6/ - the guy maintaining that project is being very pro-active about making sure it is the latest version of JDT in there (he recently did the upgrade to the latest neon JDT). I'd be very interested to know if that fixes things or not for you. If it doesn't I will raise a bug for him to look at. Or Martin - if you are setup and can try the latest?

**Comment by dsyer** [comment] 2017-01-05 16:53
Thanks for the info. I already had that update site. I pulled the latest from there and the problem doesn't go away.

**Comment by spring-issuemaster** [comment] 2017-01-05 17:00
(comment in Pivotal Tracker added by Martin Lippert:) 

I installed Groovy-Eclipse today and it was a version from 2017-01-05 as far as I remember. That version broke the refactoring.

**Comment by aclement** [comment] 2017-01-05 17:03
I've raised https://github.com/groovy/groovy-eclipse/issues/253 against greclipse.

**Comment by aclement** [comment] 2017-01-05 17:35
Yes, it was something changed recently in the jdt patch to fix a greclipse issue. Should be fixed up soon.

**Comment by spring-issuemaster** [comment] 2017-01-06 08:35
(comment in Pivotal Tracker added by Martin Lippert:) 

This is fixed in Groovy-Eclipse. Please do a check for updates or install the latest version from the above mentioned update site. The version that I tested a moment ago is: 2.9.2.xx-201701052353-e46 and that fixes the issue with the extract local variable refactoring.

**Closed** 2017-01-06 08:35 UTC
Labels: accepted
