### ISSUE TITLE
STS hangs when right clicked on a project

### ISSUE THREAD

**Issue by haimullapudi** [spring-projects/spring-ide#102] opened 2017-03-24 03:12 UTC
I am using 3.8.3.RELEASE on Windows 7 64-bit.

I am having this issue inside VPN where I do not have access to the internet, it works fine outside the VPN.
Attached below is the thread dump.

[Thread dump_sts_hangs_on_proj_right_click.txt](https://github.com/spring-projects/spring-ide/files/866760/Thread.dump_sts_hangs_on_proj_right_click.txt)

**Comment by martinlippert** [comment] 2017-03-27 13:58
This is a duplicate of https://issuetracker.springsource.com/browse/STS-4431 and already fixed for the upcoming 3.8.4 release. Therefore closing this one here. Thanks for reporting and attaching the thread dump. That made it a lot easier to figure out what problem this is. Thanks!!!

**Closed by martinlippert** 2017-03-27 13:58 UTC
