### ISSUE TITLE
Navigation inside xml file doesn't work

### ISSUE THREAD

**Issue by fkomar** [spring-projects/spring-ide#345] opened 2019-02-12 22:13 UTC
If I'm inside big spring xml file and I use F3 to jump to bean declaration. After that I use Alt + left arrow and expect to get back to previous position inside that same xml file. Instead I get back to previous position in java file.

**Comment by BoykoAlex** [comment] 2019-05-10 05:00
The problem is that XML editor is a multipage editor and Eclipse's navigation history doesn't seem to record proper editor ID in this case. Need to raise eclipse bugzilla for this I think

**Comment by martinlippert** [comment] 2019-05-10 06:48
So closing this here and removing the release milestone marker again.
@fkomar please open a bug for this at https://bugs.eclipse.org/bugs/enter_bug.cgi?product=Platform

**Closed by martinlippert** 2019-05-10 06:48 UTC
