### ISSUE TITLE
STS 3.9.0 - VM args for keystores throws UnrecoverableKeyException after update

### ISSUE THREAD

**Issue by KoChris** [spring-projects/spring-ide#162] opened 2017-07-11 20:30 UTC
Hi,

I'm using the local spring boot server to run an app connecting to a downstream webservice with 2 way ssl. 

I set the keystore and truststores in the vm args in the run configurations.
-Djavax.net.ssl.keyStore
-Djavax.net.ssl.keyStorePassword
-Djavax.net.ssl.trustStore
-Djavax.net.ssl.trustStorePassword

My service calls worked without any problems in version 3.8.4 but after the update, I am getting 

java.security.UnrecoverableKeyException: Password verification failed
	at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:778) ~[na:1.8.0_91]
	at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:56) ~[na:1.8.0_91]
	at sun.security.provider.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:224) ~[na:1.8.0_91]
	at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(JavaKeyStore.java:70) ~[na:1.8.0_91]
	at java.security.KeyStore.load(KeyStore.java:1445) ~[na:1.8.0_91]
	at sun.security.ssl.TrustManagerFactoryImpl.getCacertsKeyStore(TrustManagerFactoryImpl.java:226) ~[na:1.8.0_91]
	at sun.security.ssl.SSLContextImpl$DefaultSSLContext.getDefaultTrustManager(SSLContextImpl.java:767) ~[na:1.8.0_91]
	at sun.security.ssl.SSLContextImpl$DefaultSSLContext.<init>(SSLContextImpl.java:733) ~[na:1.8.0_91]

I have tried both:
- updating STS from version 3.8.4 using the 'Check for update function' in eclipse NEON
- downloading STS v3.9.0 fresh from spring and running the same project

I have also tried deleting and recreating the run configuration without any luck. 

Please help

**Comment by kdvolder** [comment] 2017-07-11 20:33
I wonder if maybe this is caused by this: #159

**Comment by r-b-james** [comment] 2017-07-11 20:42
#159 looks the same to me.  I'm finding that the last VM arg I specify in my run configuration has "-noverify" appended to its value.  I've worked around this by adding an extra "-Dthis.is.something.that.wont.matter=true" to the end of my VM args.  Just an extra argument that won't have any effect.

**Comment by kdvolder** [comment] 2017-07-11 20:44
Okay. Great you found a workaround. I will close this ticket as a duplicate of the other now.

**Closed by kdvolder** 2017-07-11 20:44 UTC
