### ISSUE TITLE
Request Mappings View not scrollable

### ISSUE THREAD

**Issue by imod** [spring-projects/spring-ide#243] opened 2018-02-28 11:02 UTC
Hi,

I have a Spring Boot project that has quite a lot of request mappings.
All of them are listed nicely in "Properties > Request Mappings", but unfortunate I'm not able to scroll this view. Whenever I try, it just snaps back to the first.

Version: 3.9.2.RELEASE
Build Id: 201712210947
Platform: Eclipse Oxygen.2 (4.7.2)

**Comment by kdvolder** [comment] 2018-02-28 16:28
Works for me. on STS 4.0.0.M9.  Tested on Ubuntu 16.04. 
I will also test this with a STS 3.9.x version.

In case this is OS specific. What OS are you on?

**Comment by kdvolder** [comment] 2018-02-28 16:32
Was able to reproduce on STS 3.9.x (CI build). It actually does work, but only after resizing STS window. Prior to resizing the window the scrollbar did not appear on the Requestmapping table viewer.

**Comment by kdvolder** [comment] 2018-02-28 16:39
Seems to be a problem only the first time the view is shown. After a single resize, seems to work properly. Even repeatedly closing / reopening the page... it seems the scrollbar is fine.

**Comment by imod** [comment] 2018-02-28 22:02
Yes, I can confirm it works, but I had to resize and switch between General and Request Mapping and back until it actually worked

**Comment by kdvolder** [comment] 2018-03-01 00:44
Okay thanks for confirming, souns like you are seeing similar behavior where it is initially broken until something forces it somehow to redraw or reflow. BTW: please don't misunderstand, this behavior is definitely something we'd consider a bug and should be fixed. I just had a bit of problem reproducing it at first because it 'seemed to work' until I figured out you have to be a little careful at first not to drag stuff around first or the bug does not manifest itself.

**Closed** 2018-03-12 15:05 UTC
Labels: delivered
